Repository stolostron/ocp4-azure-ipi, pull requests merged in 2022-05, with the labels that each got.

#2 Expose bastion image config as variables
  roles/ocp4-cloud-ipi/tasks/azure-bastion-infra.yml
  vars/vars-disconnected.yml
  vars/vars-private.yml
Labels: lgtm

#1 Document SSH keys prerequirements + check that they are satisfied
  docs/prereqs.md
  roles/ocp4-cloud-ipi/tasks/check-prereqs.yml
  roles/ocp4-cloud-ipi/tasks/main.yml
Labels: lgtm

#3 Add some useful tagging on Bastion VMs
  .gitignore
  roles/ocp4-cloud-ipi/tasks/azure-bastion-infra.yml
Labels: lgtm

#5 Expose a few more variables for a RHEL bastion deployment
  roles/ocp4-cloud-ipi/tasks/azure-bastion-infra.yml
  roles/ocp4-cloud-ipi/tasks/bastion-packages.yml
  vars/vars-disconnected.yml
  vars/vars-private-rhel.yml
  vars/vars-private.yml
Labels: lgtm, approved

#7 allow cluster rg name
  .gitignore
  roles/ocp4-cloud-ipi/tasks/install.yml
  roles/ocp4-cloud-ipi/templates/install-config-private.yaml.j2
  vars/vars-private-rhel.yml
Labels: approved

#6 Open port 5000 on bastion only in case of disconnected install
  roles/ocp4-cloud-ipi/tasks/azure-bastion-infra.yml
  roles/ocp4-cloud-ipi/tasks/install.yml
  vars/vars-private-rhel.yml
Labels: approved

#8 Add support for NAT Gateway for egress
  docs/egress-nat.md
  install-private.yml
  roles/ocp4-cloud-ipi/tasks/azure-infra-nat-gateway.yml
  roles/ocp4-cloud-ipi/tasks/main.yml
  vars/vars-nat-gateway.yml
Labels: lgtm, approved

#9 Add support for AAP
  install-private.yml
  roles/ocp4-cloud-ipi/tasks/azure-infra-nat-gateway.yml
  roles/ocp4-cloud-ipi/tasks/handle-prereqs.yml
  roles/ocp4-cloud-ipi/tasks/main.yml
  roles/ocp4-cloud-ipi/templates/private_ssh_key.j2
  roles/ocp4-cloud-ipi/templates/public_ssh_key.j2
  uninstall-private.yml
Labels: lgtm, approved
